name = "action"
version = "1.0.0"
description = "A Gleam web application"

[dependencies]
gleam_stdlib = "~> 0.29"
mist = "~> 0.13"
sqlight = "~> 0.6"
ids = "~> 0.7"
framework = { path = "../framework" }
htmb = { path = "../htmb" }

[dev-dependencies]
gleeunit = "~> 0.10"
